### ISSUE TITLE
NadeOCR not spanning over multiple monitors

### ISSUE THREAD

**Issue by davafons** [Natsume-197/NadeOCR#5]
## Actual Behavior

When using the `Scan` feature to capture the screen, NadeOCR only is displayed over the leftmost monitor (it doesn't matter if that monitor is marked as primary or secondary).

## Expected Behavior

When using the `Scan` feature to capture the screen, NadeOCR should either:

a) Span the grayed area over multiple monitors and allow capturing on any of them.

b) Follow the mouse and move the grayed area on the monitor where the mouse is at the moment.

## Environment
OS: Manjaro Gnome
Version: Latest

**Comment by Natsume-197** [comment]
Hi! Closing this as commit [ba1b795](https://github.com/Natsume-197/NadeOCR/commit/ba1b795d2bf27b33929da93954ee1277583b1e96) has been released. 

I have used as an expected behavior the approach A in order to fix this problem for one main reason, there are several people who use two or more screens with a single application in fullscreen mode. 

Thanks for reporting this bug! 
You are free to re-open this if your issue has not been solved.
